alias: Christmas Lights Off
trigger:
- event: sunrise
  platform: sun
  offset: "01:00:00"
- platform: time
  at: "23:30:00"
condition:
action:
- service: switch.turn_off
  entity_id: 
  - switch.christmas_indoor_sonoff
  - switch.christmas_outside