alias: Toilet Motion Turn On Lights
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/toilet_motion'
condition:
  condition: and 
  conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.occupancy == true }}"
  - condition: state
    entity_id: input_boolean.motion_enabled
    state: 'on'
  - condition: or
    conditions:     
      - condition: template
        value_template: "{{states('sensor.toilet_lux') | int <= states('input_number.toilet_lux_limit') | int}}"
      - condition: state
        entity_id: light.toilet
        state: 'on'
action:
- service: timer.cancel
  data:
    entity_id: timer.toilet
- service: timer.start
  data_template:
    entity_id: timer.toilet
    duration: 00:{{ '{:02}'.format(states('input_number.toilet_timeout') | int) }}:00
- condition: state
  entity_id: light.toilet
  state: 'off'
- service: switch.turn_on
  entity_id: switch.toilet
- service: light.turn_on
  data_template:
    entity_id: light.toilet
    brightness_pct: "{{ state_attr('switch.circadian_lighting_circadian_lighting', 'brightness') | int }}"