alias: Toilet Timer
initial_state: true
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.toilet
condition: []
action:
- service: light.turn_off
  data:
    entity_id: light.toilet
    transition: 3