alias: Landing Motion Turn On Lights
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/landing_motion'
condition:
  condition: and 
  conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.occupancy == true }}"
  - condition: or
    conditions:     
      - condition: template
        value_template: "{{states('sensor.landing_lux') | int <= states('input_number.landing_lux_limit') | int}}"
      - condition: state
        entity_id: light.landing
        state: 'on'
action:
- service: timer.cancel
  data:
    entity_id: timer.landing
- service: timer.start
  data_template:
    entity_id: timer.landing
    duration: 00:{{ '{:02}'.format(states('input_number.landing_timeout') | int) }}:00
- condition: state
  entity_id: light.landing
  state: 'off'
- service: switch.turn_on
  entity_id: switch.landing
- service: light.turn_on
  data_template:
    entity_id: light.landing
    brightness_pct: >
      {% set hour=states("sensor.time").split(':')[0] | int %}
      {% if hour >= 5 and hour < 8 %}
        30
      {% elif hour >= 8 and hour < 19 %}
        100
      {% elif hour >= 19 and hour < 22 %}
        10
      {% else %}
        1
      {% endif %}