alias: Porch front door open
initial_state: true
trigger:
- platform: state
  entity_id: sensor.front_door_contact
  to: 'on'
condition:
- condition: state
  entity_id: binary_sensor.night
  state: 'on'
- condition: state
  entity_id: light.porch
  state: 'off'
action:
- service: light.turn_on
  data_template:
    entity_id: light.porch
    brightness_pct: "{{ state_attr('switch.circadian_lighting_circadian_lighting', 'brightness') | int }}"
- service: timer.cancel
  data:
    entity_id: timer.porch
- service: timer.start
  data:
    entity_id: timer.porch
    duration: 00:03:00