alias: Porch on Ring Ding
initial_state: true
trigger:
- platform: state
  entity_id: binary_sensor.ring_front_door_heybridge_ding
  to: 'on'
condition:
- condition: state
  entity_id: binary_sensor.night
  state: 'on'
action:
- delay: '00:00:05'
- service: light.turn_on
  entity_id: light.entrance
- delay: '00:00:01'
- service: light.turn_on
  data_template:
    entity_id: light.porch
    brightness_pct: >
      {% set hour=states("sensor.time").split(':')[0] | int %}
      {% if hour >= 5 and hour < 8 %}
        30
      {% elif hour >= 8 and hour <21 %}
        100
      {% elif hour >= 21 and hour <24 %}
        30
      {% else %}
        10
      {% endif %}
    transition: 1
- service: timer.cancel
  data:
    entity_id: timer.entrance
- service: timer.start
  data:
    entity_id: timer.entrance
    duration: 00:05:00
- service: timer.cancel
  data:
    entity_id: timer.porch
- service: timer.start
  data:
    entity_id: timer.porch
    duration: 00:03:00