alias: Lounge Reached Temperature
trigger:
  platform: time_pattern
  minutes: /5
condition:
  - condition: template
    value_template: "{{ not is_state('climate.melcloud_lounge_174962', 'off') }}"
  - condition: template
    value_template: "{{ (state_attr('climate.melcloud_lounge_174962', 'temperature') | float - (state_attr('climate.melcloud_lounge_174962', 'current_temperature') | float) ) | abs < 1 }}"
action:
  - service: climate.turn_off
    entity_id: climate.melcloud_lounge_174962