id: play_sky_1_at_night_when_away
alias: Play Sky 1 at night when away
trigger:
- minutes: /15
  platform: time_pattern
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{ not is_state(''media_player.lounge_atv'', ''playing'') }}'
  - condition: sun
    after: sunset
  - condition: state
    entity_id: alarm_control_panel.yale_smart_alarm
    state: armed_away
action:
- service: script.turn_on_lounge_media
- service: script.lounge_media_play_sky1