downstairs_lights:
  name: "Downstairs Lights"
  entities:
    - light.entrance
    - light.toilet
    - light.kitchen
    - light.under_counter_lights
    - light.floor
    - light.lounge
    - light.dining
    - light.porch
    - light.utility
    - switch.fish

upstairs_lights:
  name: "Upstairs Lights"
  entities:
    - light.landing
    - light.bathroom
    - light.master
    - light.jayden
    - light.jayden_bedside
    - light.aaron
    - light.master
    - light.office
    - light.master_accent

downstairs_switches:
  name: "Downstairs Switches"
  entities:
    - switch.toilet
    - switch.floor
    - switch.fish
    - switch.dining
    - switch.lounge

upstairs_switches:
  name: "Upstairs Switches"
  entities:
    - switch.landing
    - switch.bathroom
    - switch.jayden
    - switch.master

light_timers:
  name: Light Timers
  entities:
    # downstairs
    - timer.toilet
    - timer.kitchen
    - timer.lounge
    - timer.dining
    - timer.entrance
    - timer.porch
    - timer.utility
    # upstairs
    - timer.landing
    - timer.bathroom
    - timer.jayden_bedroom
    - timer.aaron_bedroom
    - timer.main_bedroom
    - timer.office
    - timer.aaron
contact_timers:
  name: Contact Timers
  entities:
    # doors
    - timer.front_door
    - timer.back_door
    - timer.patio_door
    - timer.toilet_window
    - timer.kitchen_window
    - timer.lounge_windows

doors:
  name: Doors
  entities:
    - binary_sensor.xiaomi_front_door_contact
    - binary_sensor.xiaomi_back_door_contact
    - binary_sensor.xiaomi_patio_door_contact
    - binary_sensor.lounge_left_window
    - binary_sensor.lounge_right_window
    - binary_sensor.toilet_window
    - binary_sensor.kitchen_window

motion:
  name: Motion
  entities:
    - binary_sensor.bathroom_motion
    - binary_sensor.toilet_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.utility_motion
    - binary_sensor.master_motion
    - binary_sensor.dining_motion
    - binary_sensor.lounge_motion
    - binary_sensor.ring_garage_motion
    - binary_sensor.ring_front_door_motion
    - binary_sensor.landing_motion
    - binary_sensor.jayden_motion
    
batteries:
  name: Batteries
  entities:
    - sensor.bathroom_motion_battery
    - sensor.toilet_motion_battery
    - sensor.kitchen_motion_battery
    - sensor.landing_motion_battery
    - sensor.jayden_motion_battery

linkquality:
  name: Linkquality
  entities:
    - sensor.bathroom_motion_linkquality
    - sensor.toilet_motion_linkquality
    - sensor.kitchen_motion_linkquality
    - sensor.landing_motion_linkquality
    - sensor.jayden_motion_linkquality

ring_heybridge:
  name: Ring Heybridge
  entities:
    - sensor.ring_front_door_heybridge_last_motion
    - sensor.ring_front_door_heybridge_last_ding
    - sensor.ring_garage_last_motion

ring_mum:
  name: Ring Mum
  entities:
    - sensor.ring_front_door_last_motion
    - sensor.ring_front_door_last_ding

system:
  name: System
  entities:
    - script.restart_hass