  include:
    entities:
      - alarm_control_panel.yale_smart_alarm
      - climate.entryway
      - device_tracker.eugene
      - binary_sensor.eugene
      - device_tracker.hailey
      - binary_sensor.hailey
      - device_tracker.aubrecia
      - device_tracker.malcolm
      - group.all_devices
      - group.all_lights
      - group.all_switches
      - group.downstairs_lights
      - group.upstairs_lights
      - light.bathroom
      - light.floor_light
      - light.front_door
      - light.jayden_bed_light
      - light.kitchen
      - light.landing
      - light.toilet
      - light.under_counter_lights
      - sensor.entryway_thermostat_humidity
      - sensor.entryway_thermostat_operation_mode
      - sensor.entryway_thermostat_target
      - sensor.entryway_thermostat_temperature
      - sensor.eugene_battery_level
      - sensor.eugene_battery_state
      - sensor.hailey_battery_level
      - sensor.hailey_battery_state
      - sun.sun
