# - platform: mqtt
#   name: Toilet
#   command_topic: "zigbee2mqtt/toilet_light/set"
#   state_topic: "zigbee2mqtt/toilet_light"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   brightness: true
#   rgb: false
#   schema: json
- platform: mqtt
  name: "Dining"
  schema: json
  command_topic: "zigbee2mqtt/dining_group/set"
  state_topic: "zigbee2mqtt/dining_group"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Dining1"
  schema: json
  command_topic: "zigbee2mqtt/dining1_light/set"
  state_topic: "zigbee2mqtt/dining1_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Dining2"
  schema: json
  command_topic: "zigbee2mqtt/dining2_light/set"
  state_topic: "zigbee2mqtt/dining2_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Dining3"
  schema: json
  command_topic: "zigbee2mqtt/dining3_light/set"
  state_topic: "zigbee2mqtt/dining3_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Dining4"
  schema: json
  command_topic: "zigbee2mqtt/dining4_light/set"
  state_topic: "zigbee2mqtt/dining4_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Dining5"
  schema: json
  command_topic: "zigbee2mqtt/dining5_light/set"
  state_topic: "zigbee2mqtt/dining5_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
# - platform: mqtt
#   name: "Porch"
#   schema: json
#   command_topic: "zigbee2mqtt/porch_light/set"
#   state_topic: "zigbee2mqtt/porch_light"
#   brightness: true
#   color_temp: false
#   qos: 2
#   optimistic: false
- platform: mqtt
  name: "Floor"
  schema: json
  command_topic: "zigbee2mqtt/floor_light/set"
  state_topic: "zigbee2mqtt/floor_light"
  brightness: true
  color_temp: false
  qos: 2
  optimistic: false
# - platform: mqtt
#   name: "Landing"
#   schema: json
#   command_topic: "zigbee2mqtt/landing_light/set"
#   state_topic: "zigbee2mqtt/landing_light"
#   brightness: true
#   color_temp: false
#   qos: 2
#   optimistic: false
# - platform: mqtt
#   name: "Utility"
#   schema: json
#   command_topic: "zigbee2mqtt/utility_light/set"
#   state_topic: "zigbee2mqtt/utility_light"
#   brightness: true
#   color_temp: true
#   qos: 2
#   optimistic: false
- platform: mqtt
  name: "Aaron"
  schema: json
  command_topic: "zigbee2mqtt/aaron_light/set"
  state_topic: "zigbee2mqtt/aaron_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Study"
  schema: json
  command_topic: "zigbee2mqtt/study_group/set"
  state_topic: "zigbee2mqtt/study_group"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Study1"
  schema: json
  command_topic: "zigbee2mqtt/study1_light/set"
  state_topic: "zigbee2mqtt/study1_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Study2"
  schema: json
  command_topic: "zigbee2mqtt/study2_light/set"
  state_topic: "zigbee2mqtt/study2_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Study3"
  schema: json
  command_topic: "zigbee2mqtt/study3_light/set"
  state_topic: "zigbee2mqtt/study3_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Jayden"
  schema: json
  command_topic: "zigbee2mqtt/jayden_light/set"
  state_topic: "zigbee2mqtt/jayden_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Office"
  schema: json
  command_topic: "zigbee2mqtt/office_light/set"
  state_topic: "zigbee2mqtt/office_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false
- platform: mqtt
  name: "Master"
  schema: json
  command_topic: "zigbee2mqtt/master_light/set"
  state_topic: "zigbee2mqtt/master_light"
  brightness: true
  color_temp: true
  qos: 2
  optimistic: false