exclude:
  entities:
    - binary_sensor.ring_front_door_motion
    - binary_sensor.ring_garage_motion
    - group.away_random_lights
    - group.home_random_lights
    - sensor.eugene_battery_state
    - sensor.eugene_battery_level
    - sensor.hailey_battery_state
    - sensor.hailey_battery_level
    - sensor.met_office_feels_like_temperature
    - sensor.met_office_humidity
    - sensor.met_office_probability_of_precipitation
    - sensor.met_office_temperature
    - sensor.met_office_uv
    - sensor.met_office_visibility
    - sensor.met_office_visibility_distance
    - sensor.met_office_weather
    - sensor.met_office_wind_direction
    - sensor.met_office_wind_gust
    - sensor.met_office_wind_speed
    - sensor.time
    - sensor.date
    - sensor.time_utc
    - sensor.time_date
    - sensor.date_time
    - switch.sonoff_1000315c97
    - switch.sonoff_100031bfb1
    - switch.sonoff_100031bfbd
    - script.tts_all
    - script.tts_kitchen
    - script.tts_upstairs
    - sensor.jayden_vibration_action
    - sensor.jayden_vibration_battery
    - sensor.jayden_vibration_linkquality
    - sensor.jayden_vibration_linkquality_2
    - sensor.jayden_vibration_action
    - sensor.jayden_vibration_battery
    - sensor.jayden_vibration_linkquality
    - sensor.jayden_vibration_action_2
    - sensor.jayden_vibration_battery_2
    - sensor.jayden_vibration_linkquality_2
