- platform: template
  sensors:
    master_climate_state:
      friendly_name: Master Climate State
      value_template: "{{ states('climate.melcloud_master_176430') }}"
    lounge_climate_state:
      friendly_name: Lounge Climate State
      value_template: "{{ states('climate.melcloud_lounge_174962') }}"
    aaron_climate_state:
      friendly_name: Aaron Climate State
      value_template: "{{ states('climate.melcloud_aaron_177590') }}"
    jayden_climate_state:
      friendly_name: Jayden Climate State
      value_template: "{{ states('climate.melcloud_jayden_177589') }}"
    avg_current_temperature:
      friendly_name: Average Current Temperature
      unit_of_measurement: "°C"
      value_template: >-
        {{ (
             (
               float(state_attr('climate.melcloud_master_176430', 'current_temperature')) + 
               float(state_attr('climate.melcloud_lounge_174962', 'current_temperature')) + 
               float(state_attr('climate.melcloud_aaron_177590', 'current_temperature')) + 
               float(state_attr('climate.melcloud_jayden_177589', 'current_temperature'))
             ) / 4
           ) | round(1) }}