- platform: mqtt
  name: Sprinkler Right Power
  state_topic: "shellies/shellyswitch25-BA86C3/relay/0/power"
  unit_of_measurement: "Watts"
- platform: mqtt
  name: Sprinkler Left Power
  state_topic: "shellies/shellyswitch25-BA86C3/relay/1/power"
  unit_of_measurement: "Watts"
- platform: mqtt
  name: Sprinkler Right Energy
  state_topic: "shellies/shellyswitch25-BA86C3/relay/0/energy"
  unit_of_measurement: "Watt-min"
- platform: mqtt
  name: Sprinkler Left Energy
  state_topic: "shellies/shellyswitch25-BA86C3/relay/1/energy"
  unit_of_measurement: "Watt-min"

- platform: mqtt
  name: Dishwasher Power
  state_topic: "shellies/shellyswitch25-BA7719/relay/0/power"
  unit_of_measurement: "Watts"
- platform: mqtt
  name: Dryer Power
  state_topic: "shellies/shellyswitch25-BA7719/relay/1/power"
  unit_of_measurement: "Watts"
- platform: mqtt
  name: Dishwasher Energy
  state_topic: "shellies/shellyswitch25-BA7719/relay/0/energy"
  unit_of_measurement: "Watt-min"
- platform: mqtt
  name: Dryer Energy
  state_topic: "shellies/shellyswitch25-BA7719/relay/1/energy"
  unit_of_measurement: "Watt-min"

- platform: mqtt
  name: Plug 1 Energy
  state_topic: "plug/tele/smart_plug_1/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "Watts"

- platform: mqtt
  name: Plug 2 Energy
  state_topic: "plug/tele/smart_plug_2/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "Watts"

- platform: mqtt
  name: Plug 3 Energy
  state_topic: "plug/tele/smart_plug_3/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "Watts"

- platform: mqtt
  name: Plug 4 Energy
  state_topic: "plug/tele/smart_plug_4/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "Watts"

- platform: mqtt
  name: Plug 5 Energy
  state_topic: "plug/tele/smart_plug_5/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "Watts"

- platform: mqtt
  name: Plug 1 Current
  state_topic: "plug/tele/smart_plug_1/SENSOR"
  value_template: "{{ value_json.ENERGY.Current }}"
  unit_of_measurement: "Amps"

- platform: mqtt
  name: Plug 2 Current
  state_topic: "plug/tele/smart_plug_2/SENSOR"
  value_template: "{{ value_json.ENERGY.Current }}"
  unit_of_measurement: "Amps"

- platform: mqtt
  name: Plug 3 Current
  state_topic: "plug/tele/smart_plug_3/SENSOR"
  value_template: "{{ value_json.ENERGY.Current }}"
  unit_of_measurement: "Amps"

- platform: mqtt
  name: Plug 4 Current
  state_topic: "plug/tele/smart_plug_4/SENSOR"
  value_template: "{{ value_json.ENERGY.Current }}"
  unit_of_measurement: "Amps"

- platform: mqtt
  name: Plug 5 Current
  state_topic: "plug/tele/smart_plug_5/SENSOR"
  value_template: "{{ value_json.ENERGY.Current }}"
  unit_of_measurement: "Amps"

- platform: mqtt
  name: Plug 1 Voltage
  state_topic: "plug/tele/smart_plug_1/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "Volts"

- platform: mqtt
  name: Plug 2 Voltage
  state_topic: "plug/tele/smart_plug_2/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "Volts"

- platform: mqtt
  name: Plug 3 Voltage
  state_topic: "plug/tele/smart_plug_3/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "Volts"

- platform: mqtt
  name: Plug 4 Voltage
  state_topic: "plug/tele/smart_plug_4/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "Volts"

- platform: mqtt
  name: Plug 5 Voltage
  state_topic: "plug/tele/smart_plug_5/SENSOR"
  value_template: "{{ value_json.ENERGY.Voltage }}"
  unit_of_measurement: "Volts"