- platform: "mqtt"
  name: Fish Vibration Action
  state_topic: "zigbee2mqtt/fish_vibration"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:gesture-double-tap"
  value_template: "{{ value_json.action }}"

- platform: "mqtt"
  name: Fish Vibration Battery
  state_topic: "zigbee2mqtt/fish_vibration"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: Post Vibration Action
  state_topic: "zigbee2mqtt/post_vibration"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:gesture-double-tap"
  value_template: "{{ value_json.action }}"

- platform: "mqtt"
  name: Post Vibration Battery
  state_topic: "zigbee2mqtt/post_vibration"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
