- platform: mqtt
  name: Landing
  state_topic: "shellies/shelly1-2C843B/relay/0"
  command_topic: "shellies/shelly1-2C843B/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: Toilet
  state_topic: "shellies/shelly1-2C7EE1/relay/0"
  command_topic: "shellies/shelly1-2C7EE1/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: Dining
  state_topic: "shellies/shelly1-2C0B7F/relay/0"
  command_topic: "shellies/shelly1-2C0B7F/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: Bathroom
  state_topic: "shellies/shelly1-2C7BD4/relay/0"
  command_topic: "shellies/shelly1-2C7BD4/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: Jayden
  state_topic: "shellies/shelly1-554EF2/relay/0"
  command_topic: "shellies/shelly1-554EF2/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: Master
  state_topic: "shellies/shelly1-55E8B5/relay/0"
  command_topic: "shellies/shelly1-55E8B5/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: SprinklerRight
  state_topic: "shellies/shellyswitch25-BA86C3/relay/0"
  command_topic: "shellies/shellyswitch25-BA86C3/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: SprinklerLeft
  state_topic: "shellies/shellyswitch25-BA86C3/relay/1"
  command_topic: "shellies/shellyswitch25-BA86C3/relay/1/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: Dishwasher
  state_topic: "shellies/shellyswitch25-BA7719/relay/0"
  command_topic: "shellies/shellyswitch25-BA7719/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
- platform: mqtt
  name: Dryer
  state_topic: "shellies/shellyswitch25-BA7719/relay/1"
  command_topic: "shellies/shellyswitch25-BA7719/relay/1/command"
  payload_on: "on"
  payload_off: "off"
  retain: false