alias: Dining Timer
initial_state: true
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.dining
condition: []
action:
- service: light.turn_on
  data_template:
    entity_id: light.dining
    brightness_pct: 0
    transition: 5