alias: Kitchen Timer
initial_state: true
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.kitchen
condition: []
action:
- service: light.turn_off
  entity_id: light.kitchen
- service: light.turn_off
  entity_id: light.under_counter_lights