alias: Watchdog
initial_state: true
trigger:
- platform: time_pattern
  hours: /1
condition:
action:
- service: script.speech_engine
  data:
    call_window_check: 1
    call_door_check: 1
    call_check_lights: 1