alias: Location Update
initial_state: true
trigger:
- entity_id: device_tracker.eugene, device_tracker.hailey
  platform: state
condition: 
  - condition: template
    value_template: "{{ trigger.to_state.state != 'not_home' and trigger.to_state.state != 'home' }}"
  - condition: and
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == 'device_tracker.eugene' and trigger.to_state.state != states.input_text.eugene_location.state }}" 
          - condition: template
            value_template: "{{ trigger.entity_id == 'device_tracker.hailey' and trigger.to_state.state != states.input_text.hailey_location.state }}" 
action:
- service: input_text.set_value
  data_template:
    entity_id: "{{ 'input_text.eugene_location' if trigger.entity_id == 'device_tracker.eugene' else 'input_text.hailey_location'}}"
    value: "{{ trigger.to_state.state }}"
- service: script.tts_all
  data_template:
    message: "{{ trigger.to_state.attributes.friendly_name }}'s location is: {{ trigger.to_state.state }}"
- service_template: notify.{% if trigger.entity_id == 'device_tracker.eugene' %}ios_hailey{% else %}ios_eugene{% endif %}
  data_template:
    message: "{{ trigger.to_state.attributes.friendly_name }}'s location is: {{ trigger.to_state.state }}"
