id: work_routine_alarm
alias: Work Routine Alarm
trigger:
- platform: time_pattern
  minutes: /5
condition:
  condition: and
  conditions:
  - condition: time
    after: 05:00:00
    before: 06:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: input_boolean.work_tomorrow
    state: 'on'
action:
- service: media_player.volume_set
  data_template:
    entity_id: media_player.upstairs
    volume_level: >
      {% set minute=now().minute | int %}
      {% if minute >= 0 and minute < 5 %}
        0.1
      {% elif minute >= 5 and minute < 10 %}
        0.2
      {% elif minute >= 10 and minute < 15 %}
        0.3
      {% elif minute >= 15 and minute < 20 %}
        0.4
      {% elif minute >= 20 and minute < 25 %}
        0.5
      {% elif minute >= 25 and minute < 30 %}
        0.6
      {% elif minute >= 30 %}
        0.7
      {% else %}
        0.3
      {% endif %}
- service: notify.alexa_media
  data_template:
    target: 
      - media_player.master
    data:
      type: announce
    message: Wake up... the time is {{ now().minute }} past {{ now().hour }}
initial_state: true