alias: fish Motion Turn On Lights
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/lounge_motion'
- platform: mqtt
  topic: 'zigbee2mqtt/dining_motion'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ trigger.payload_json.occupancy == true }}"
action:
- service: timer.cancel
  data:
    entity_id: timer.fish
- service: timer.start
  data:
    entity_id: timer.fish
    duration: 00:30:00
- condition: state
  entity_id: switch.fish
  state: 'off'
- service: switch.turn_on
  entity_id: switch.fish