id: random_home_lights
alias: Random home lights
initial_state: true
trigger:
- minutes: '/15'
  platform: time_pattern
condition:
- condition: state
  entity_id: input_boolean.is_bedtime
  state: 'on'
- condition: state
  entity_id: binary_sensor.night
  state: 'on'
action:
- delay: "00:{{ '{:02}'.format(range(1,10) | random | int) }}:00"
- data_template:
    entity_id: '{{ states.group.home_random_lights.attributes.entity_id | random }}'
  service: homeassistant.toggle
