alias: Utility Motion Turn On Lights
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/utility_motion'
condition:
  condition: and 
  conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.occupancy == true }}"
  - condition: or
    conditions:     
      - condition: template
        value_template: "{{states('sensor.utility_lux') | int <= states('input_number.master_lux_limit') | int}}"
      - condition: state
        entity_id: light.utility
        state: 'on'
action:
- service: timer.cancel
  data:
    entity_id: timer.utility
- service: timer.start
  data_template:
    entity_id: timer.utility
    duration: 00:{{ '{:02}'.format(states('input_number.utility_timeout') | int) }}:00
- condition: state
  entity_id: light.utility
  state: 'off'
- service: light.turn_on
  data_template:
    entity_id: light.utility
    brightness_pct: >
      {% set hour=states("sensor.time").split(':')[0] | int %}
      {% if hour >= 5 and hour < 8 %}
        30
      {% elif hour >= 8 and hour <21 %}
        100
      {% elif hour >= 21 and hour <24 %}
        10
      {% else %}
        1
      {% endif %}