# Contact
- platform: "mqtt"
  name: Front Door
  state_topic: "zigbee2mqtt/front_door"
  value_template: "{{ value_json.contact }}"
  device_class: door
- platform: "mqtt"
  name: Dining Door
  state_topic: "zigbee2mqtt/dining_door"
  value_template: "{{ value_json.contact }}"
  device_class: door
- platform: "mqtt"
  name: Lounge Door
  state_topic: "zigbee2mqtt/lounge_door"
  value_template: "{{ value_json.contact }}"
  device_class: door
- platform: "mqtt"
  name: Toilet Window
  state_topic: "zigbee2mqtt/toilet_window"
  value_template: "{{ value_json.contact }}"
  device_class: window
- platform: "mqtt"
  name: Lounge Left Window
  state_topic: "zigbee2mqtt/lounge_left_window"
  value_template: "{{ value_json.contact }}"
  device_class: window
- platform: "mqtt"
  name: Lounge Right Window
  state_topic: "zigbee2mqtt/lounge_right_window"
  value_template: "{{ value_json.contact }}"
  device_class: window
- platform: "mqtt"
  name: Kitchen Window
  state_topic: "zigbee2mqtt/kitchen_window"
  value_template: "{{ value_json.contact }}"
  device_class: window