- platform: bayesian
  prior: 0.5
  name: 'Eugene'
  device_class: presence
  probability_threshold: 0.8
  observations:
    - entity_id: 'device_tracker.eugene_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.eugene'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'