- platform: template
  sensors:
    niemands_home:
      friendly_name: "Niemands Home"
      device_class: presence
      value_template: >-
        {{ is_state('binary_sensor.eugene', 'on')
            or is_state('binary_sensor.hailey', 'on') }}