yamaha_tuner_on:
  alias: Turn On Radio
  sequence:
  - data:
      entity_id: media_player.yamaha_receiver
    service: media_player.turn_on
  - delay: 00:00:10
  - data:
      entity_id: media_player.yamaha_receiver
      source: TUNER
    service: media_player.select_source