alias: Entrance Motion Turn Off Bed Time
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/entrance_motion'
condition:
- condition: template
  value_template: "{{ trigger.payload_json.occupancy == true }}"
- condition: state
  entity_id: input_boolean.is_bedtime
  state: 'on'
- condition: state
  entity_id: binary_sensor.early_morning
  state: 'on'
action:
- service: input_boolean.turn_off
  entity_id: input_boolean.is_bedtime
- service: input_boolean.turn_off
  entity_id: input_boolean.work_tomorrow
- service: python_script.start_timer
  entity_id: 
    - timer.entrance
    - timer.porch
    - timer.bathroom