lounge_media_open_nowtv:
  alias: Lounge Media Open NowTV
  sequence:
  - service: script.apple_tv_reset_menu
  - wait_template: "{{ is_state('script.apple_tv_reset_menu', 'off') }}"
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - right       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - right       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - select       
  - delay: 
      milliseconds: 500  