lounge_media_play_sky1:
  alias: Lounge Media Play Sky 1
  sequence:    
  - service: script.lounge_media_open_nowtv
  - wait_template: "{{ is_state('script.lounge_media_open_nowtv', 'off') }}"
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - left       
        - left       
        - left       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - right       
  - delay: 
      seconds: 1
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - down       
  - delay: 
      seconds: 1
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - down  
        - left     
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - select       
  - delay: 
      seconds: 1
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - select       
  - delay: 
      milliseconds: 500  