alias: Aaron Motion Turn On Lights
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/aaron_motion'
condition:
  condition: and 
  conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.occupancy == true }}"
  - condition: state
    entity_id: input_boolean.motion_enabled
    state: 'on'
  - condition: or
    conditions:     
      - condition: template
        value_template: "{{states('sensor.aaron_lux') | int <= states('input_number.aaron_lux_limit') | int}}"
      - condition: state
        entity_id: light.aaron
        state: 'on'
action:
- service: timer.cancel
  data:
    entity_id: timer.aaron
- service: timer.start
  data_template:
    entity_id: timer.aaron
    duration: 00:{{ '{:02}'.format(states('input_number.aaron_timeout') | int) }}:00
- condition: state
  entity_id: light.aaron
  state: 'off'
- service: light.turn_on
  data_template:
    entity_id: light.aaron
    kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') | int }}"
    brightness_pct: "{{ state_attr('switch.circadian_lighting_circadian_lighting', 'brightness') | int }}"