- id: '1605283305465'
  alias: Tag study is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: study
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.study
  mode: single
