alias: Jayden Timer
initial_state: true
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.jayden_bedroom
condition: []
action:
- service: light.turn_off
  entity_id: light.jayden