notification_engine:
  sequence:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.notification_message
      value: >-
        {%- macro alarm() -%}
          {%- if is_state("alarm_control_panel.yale_smart_alarm", "armed_home") -%}
            {{ [
              'Its time to arm the alarm. All Done.',
              'Alarm has been armed, Good night.'
            ]|random }}
          {%- elif is_state("alarm_control_panel.yale_smart_alarm", "armed_away") -%}
            {{ [
              'The alarm is armed in away mode. Tread Carefully.',
              'Dont move in the house alarm is on now.'
            ]|random }}
          {%- else -%}
            {{[
              'Dont worry, alarm has now been disarmed.',
              'Everything is ok and I have turned off the alarm.'
              ]|random}}
          {%- endif -%}
        {%- endmacro -%}

        {%- macro check_open_windows() -%}            
            {%- for state in states.binary_sensor -%}
                {%- if state.state == 'on' and (state.entity_id).endswith('_window') -%}
                    {{ state.entity_id|replace('binary_sensor.','')|replace('_window','')|replace('_',' ') }}{{','}}
                {%- endif -%}
            {%- endfor -%}
        {%- endmacro -%}

        {%- macro check_open_doors() -%}            
            {%- for state in states.binary_sensor -%}
                {%- if state.state == 'on' and (state.entity_id).endswith('_contact') -%}
                    {{ state.entity_id|replace('binary_sensor.','')|replace('_contact','')|replace('_',' ')|replace('xiaomi',' ') }}{{','}}
                {%- endif -%}
            {%- endfor -%}
        {%- endmacro -%}
        
        {%- macro inside_weather() -%}
          Inside the house, it is {{ states.climate.entryway.attributes['current_temperature'] }} degrees with around {{ states('sensor.entryway_thermostat_humidity') }} percent humidity.
        {%- endmacro -%}

        {%- macro thermostat_changed() -%}
          Nest set to {{ states.climate.entryway.attributes['temperature'] }} degrees. It is currenlty {{ states.climate.entryway.attributes['current_temperature'] }} degrees
        {%- endmacro -%}

        {# **************************************************** #}
        {# ********* Start the Notifications routines ********  #}
        {# **************************************************** #}
        
        {%- if call_welcome_home == 1 -%}
          Welcome home. 
        {%- endif -%}

        {%- if call_announcement == 1 -%}
          {%- if now().strftime('%H')|int < 12 and now().strftime('%H')|int >= 5 -%}
            Good morning. 
          {%- elif now().strftime('%H')|int >= 12 and now().strftime('%H')|int < 17 -%}
            Good afternoon. 
          {%- else -%}
            Good evening. 
          {%- endif -%}
        {%- endif -%}
        

        {%- if call_door_check == 1 -%}
          {% set returnVal=check_open_doors() %}
          {%- if returnVal|trim|length > 0 -%}
            Open Doors: {{returnVal}}
          {%- else -%}
            All doors closed. 
          {%- endif -%}
        {%- endif -%}

        {%- if call_window_check == 1 -%}
          {% set returnVal=check_open_windows() %}
          {%- if returnVal|trim|length > 0 -%}
            Open Windows: {{returnVal}}
          {%- else -%}
            All windows closed. 
          {%- endif -%}
        {%- endif -%}

        {%- if call_alarm_check == 1 -%}
          {{ alarm() }}
        {%- endif -%}

        {%- if call_inside_weather == 1 -%}
          {{ inside_weather() }}
        {%- endif -%}

        {%- if call_thermostat_changed == 1 -%}
          {{ thermostat_changed() }}
        {%- endif -%}

  - service: notify.iphones
    data_template:     
      message: "{{ states('input_text.notification_message') }}"
      title: >- 
        {%- if 'Open' in states('input_text.notification_message') -%}
          Warning!!!
        {%- else -%}
          All Good :)
        {%- endif -%}
      data:
        subtitle: >-
          {%- if 'Open' in states('input_text.notification_message') -%}
            Something is open
          {%- endif -%}