speech_engine:
  sequence:
  - service: input_text.set_value
    data_template:     
      entity_id: input_text.notification_message
      value: >-
        {%- macro arm_alarm() -%}
          {{ [
              'Arming the alarm now',
              'I have armed the alarm'
            ]|random }}
        {%- endmacro -%}
        
        {%- macro disarm_alarm() -%}          
          {{[
            'Disarming the alarm now',
            'I have disarmed the alarm'
            ]|random}}
        {%- endmacro -%}

        {%- macro alarm_status() -%}
          {% if is_state("alarm_control_panel.yale_smart_alarm", "armed_home") %}
              {{ arm_alarm() }}
            {% else %}
              {{ disarm_alarm() }}
            {% endif %}
        {%- endmacro -%}

        {%- macro check_open_windows() -%}            
            {%- for state in states.binary_sensor -%}
                {%- if state.state == 'on' and (state.entity_id).endswith('_window') -%}
                    {{ state.entity_id|replace('binary_sensor.','')|replace('_window','')|replace('_',' ') }}{{','}}
                {%- endif -%}
            {%- endfor -%}
        {%- endmacro -%}

        {%- macro check_open_doors() -%}            
            {%- for state in states.binary_sensor -%}
                {%- if state.state == 'on' and (state.entity_id).endswith('_contact') -%}
                    {{ state.entity_id|replace('binary_sensor.','')|replace('_contact','')|replace('_',' ')|replace('xiaomi',' ') }}{{','}}
                {%- endif -%}
            {%- endfor -%}
        {%- endmacro -%}

        {%- macro check_ligts_on() -%}            
            {%- for state in states.light-%}
                {%- if state.state == 'on' -%}
                    {{ state.entity_id|replace('light.','') }}{{','}}
                {%- endif -%}
            {%- endfor -%}
        {%- endmacro -%}
        
        {%- macro inside_weather() -%}
          Inside the house, it is {{ states.climate.entryway.attributes['current_temperature'] }} degrees with around {{ states('sensor.entryway_thermostat_humidity') }} percent humidity.
        {%- endmacro -%}

        {%- macro thermostat_changed() -%}
          Nest set to {{ states.climate.entryway.attributes['temperature'] }} degrees. It is currenlty {{ states.climate.entryway.attributes['current_temperature'] }} degrees
        {%- endmacro -%}

        {# ********************************************* #}
        {# ******** Start the Speech routines ********** #}
        {# ********************************************* #}
        {% if call_announcement == 1 %}
          {% if now().strftime('%H')|int < 12 and now().strftime('%H')|int >= 5 %}
            Good morning.
          {% elif now().strftime('%H')|int >= 12 and now().strftime('%H')|int < 17 %}
            Good afternoon.
          {% else %}
            Good evening.
          {% endif %}
        {% endif %}

        {% if call_welcome_home == 1 %}
          Welcome home.
        {% endif %}

        {% if call_alarm_check == 1 %}
          {{ alarm_status() }}
        {% endif %}
        
        {% if call_alarm_arm == 1 %}
          {{ arm_alarm() }}
        {% endif %}

        {% if call_alarm_disarm == 1 %}
          {{ disarm_alarm() }}
        {% endif %}

        {% if call_inside_weather == 1 %}
          {{ inside_weather() }}
        {% endif %}

        {% if call_ac_watchdog == 1 %}
          {% set acOnCount = states.climate | selectattr('state','eq','on') | list | count %}
          {% if acOnCount > 0 %}
            "{{acOnCount}} AC's are still on"
          {% endif %}
        {% endif %}

        {% if call_check_lights_count == 1 %}
          {% set onCount = states.lights | selectattr('state','eq','on') | list | count %}
          {% if onCount > 0 %}
            "{{onCount}} lights are still on"
          {% endif %}
        {% endif %}

        {% if call_thermostat_changed == 1 %}
          {{ thermostat_changed() }}
        {% endif %}

        {% if call_check_lights_info == 1 %}
          {% set returnVal=check_ligts_on() %}
          {% if returnVal|trim|length > 0 %}
            "Lights On: {{returnVal}}"
          {% endif %}
        {% endif %}

        {% if call_door_check == 1 %}
          {% set returnVal=check_open_doors() %}
          {% if returnVal|trim|length > 0 %}
            "Open Doors: {{returnVal}}"
          {% endif %}
        {% endif %}

        {% if call_window_check == 1 %}
          {% set returnVal=check_open_windows() %}
          {% if returnVal|trim|length > 0 %}
            "Open Windows: {{returnVal}}"
          {% endif %}
        {% endif %}

        

