tts_all:
  alias: TTS On All Echos
  sequence:
  - condition: template
    value_template: "{{ message|trim|length > 0 }}"
  - service: script.tts_store_and_set_volume
    data_template:
      device: master
  - service: script.tts_store_and_set_volume
    data_template:
      device: kitchen
  
  - service: notify.alexa_media
    data_template:
      target: 
        - media_player.kitchen
        - media_player.master
        - media_player.jayden
        - media_player.lounge
        - media_player.office
      data:
          type: announce
      message: "{{ message }}"
  
  - service: script.tts_restore_volume
    data_template:
      device: master
  - service: script.tts_restore_volume
    data_template:
      device: kitchen