tts_all:
  alias: TTS On All Echos
  sequence:
  - condition: template
    value_template: "{{ message|trim|length > 0 }}"
  - service: script.tts_store_and_set_volume
    data_template:
      device: master
  - service: script.tts_store_and_set_volume
    data_template:
      device: kitchen
  - service: script.tts_store_and_set_volume
    data_template:
      device: aaron
  - service: script.tts_store_and_set_volume
    data_template:
      device: jayden
  - service: script.tts_store_and_set_volume
    data_template:
      device: office
  - service: script.tts_store_and_set_volume
    data_template:
      device: lounge

  - delay: 
      milliseconds: 500
  
  - service: notify.alexa_media
    data_template:
      target: 
        - media_player.master
        - media_player.lounge
        - media_player.kitchen
        - media_player.office
        - media_player.jayden
        - media_player.aaro
      data:
          type: announce
      message: > 
        {% if is_state("input_boolean.kids_sleeping", "on") %}
          <amazon:effect name="whispered">{{message}}</amazon:effect>
        {% else %}
          {{message}}
        {% endif %}
  - delay: 00:00:10
  
  - service: script.tts_restore_volume
    data_template:
      device: master
  - service: script.tts_restore_volume
    data_template:
      device: kitchen
  - service: script.tts_restore_volume
    data_template:
      device: aaron
  - service: script.tts_restore_volume
    data_template:
      device: jayden
  - service: script.tts_restore_volume
    data_template:
      device: office
  - service: script.tts_restore_volume
    data_template:
      device: lounge