alias: Entrance On
initial_state: true
trigger:
- platform: state
  entity_id: light.entrance
  to: 'on'
condition: []
action:
- service: timer.start
  data:
    entity_id: timer.entrance
    duration: 00:05:00