alias: Turn off lounge media when idle
initial_state: true
trigger:
- entity_id: media_player.lounge_atv
  platform: state
  from: playing
  for: 00:30:00
  to: idle
condition:
action:
- service: script.turn_off_lounge_media
  