id: random_home_lights
alias: Random home lights
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_heybridge_motion
    to: 'on'
condition:
- condition: state
  entity_id: input_boolean.is_bedtime
  state: 'on'
action:
- delay: "00:00:{{ '{:02}'.format(range(5,10) | random | int) }}"
- data_template:
    entity_id: '{{ states.group.ring_motion_random_lights.attributes.entity_id | random }}'
  service: homeassistant.toggle
- service: timer.start
  entity_id:
  - timer.entrance
  - timer.porch
  data:
    duration: 00:05:00