alias: Zigbee2Mqtt Error
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/bridge/log'
condition:
- condition: template
  value_template: "{{ 'error' in trigger.payload_json.type }}"
action:
- service: system_log.write
  data_template:
    message: "{{ trigger.payload_json }}"
    level: warning