alias: Christmas Lights On
trigger:
- event: sunset
  platform: sun
- platform: time
  at: "05:30:00"
condition:
action:
- service: switch.turn_on
  entity_id: 
  - switch.christmas_indoor_sonoff
  - switch.christmas_outside