id: '1549489222939'
initial_state: true
alias: In Bed
trigger:
- entity_id: sensor.last_indoor_motion
  platform: state
  to: binary_sensor.master_motion
  for: 00:05:00
condition:
  - condition: time
    after: '21:00:00'
    before: '05:00:00'
  - condition: state
    entity_id: binary_sensor.niemands_home
    state: 'on'
action:
- service: script.good_night