alias: Jayden Out Of Bed
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/jayden_motion'
condition:
  condition: and 
  conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.occupancy == true }}"
  - condition: time
    after: '23:00:00'
    before: '06:00:00'
action:
  - delay: 00:00:05
  - service: script.tts
    data:
      device: master
      message: "Jayden is out of bed"
  - delay: 00:00:15
  - service: script.tts
    data:
      device: master
      message: "Jayden is out of bed"