tts_all:
  alias: TTS On All Echos
  sequence:
  - condition: template
    value_template: "{{ message|trim|length > 0 }}"

  - service: scene.create
    data:
      scene_id: before_tts
      snapshot_entities: "media_player.master,media_player.lounge,media_player.kitchen,media_player.office,media_player.jayden,media_player.aaron"
  
  - service: media_player.media_pause
    entity_id:
      - media_player.master
      - media_player.lounge
      - media_player.kitchen
      - media_player.office
      - media_player.jayden
      - media_player.aaron

  - service: media_player.volume_set
    data:
      entity_id:
        - media_player.master
        - media_player.office
        - media_player.jayden
        - media_player.aaron
        - media_player.lounge
        - media_player.kitchen
      volume_level: 0.4

  - service: notify.alexa_media
    data_template:
      target: 
        - media_player.master
        - media_player.lounge
        - media_player.kitchen
        - media_player.office
        - media_player.jayden
        - media_player.aaron
      data:
          type: announce
      message: > 
        {% if is_state("input_boolean.kids_sleeping", "on") %}
          <amazon:effect name="whispered">{{message}}</amazon:effect>
        {% else %}
          {{message}}
        {% endif %}

  - delay: 00:00:05

  - service: media_player.volume_set
    data:
      entity_id:
        - media_player.master
        - media_player.office
        - media_player.jayden
        - media_player.aaron
        - media_player.lounge
        - media_player.kitchen
      volume_level: 0.1

  - service: scene.turn_on
    entity_id: scene.before_tts