#!/usr/bin/env bash
#
# Bash script to startup all components of home assistant, mostly through
# docker and checking if services are available using wait-for-it
 
declare -r DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
start() {
    sleep 5m
    cd ${DIR}
    docker-compose up -d 
}
 
stop() {
    cd ${DIR}
    docker-compose stop
}
 
case $1 in
    start) start;;
    stop) stop;;
    "") start;;
    *) echo "Usage: ./service start|stop"
esac
