alias: Kitchen Motion Turn Off Bed Time
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/kitchen_motion'
condition:
- condition: template
  value_template: "{{ trigger.payload_json.occupancy == true }}"
- condition: state
  entity_id: input_boolean.is_bedtime
  state: 'on'
- condition: state
  entity_id: binary_sensor.early_morning
  state: 'on'
action:
- service: input_boolean.turn_off
  entity_id: input_boolean.is_bedtime
