alias: Kitchen Motion Turn On Lights
initial_state: true
trigger:
- platform: mqtt
  topic: 'zigbee2mqtt/kitchen_motion'
condition:
  condition: and 
  conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.occupancy == true }}"
  - condition: or
    conditions:     
      - condition: template
        value_template: "{{states('sensor.kitchen_lux') | int <= states('input_number.kitchen_lux_limit') | int}}"
      - condition: state
        entity_id: light.kitchen
        state: 'on'
action:
- service: timer.cancel
  data:
    entity_id: timer.kitchen
- service: timer.start
  data_template:
    entity_id: timer.kitchen
    duration: 00:{{ '{:02}'.format(states('input_number.kitchen_timeout') | int) }}:00
- condition: state
  entity_id: light.kitchen
  state: 'off'
- service: light.turn_on
  entity_id: light.kitchen
- service: light.turn_on
  entity_id: light.under_counter_lights
