- platform: template
  sensors:
    last_indoor_motion:
      friendly_name: 'Last Indoor Motion'
      value_template: >
        {%- set pirs = [
          states.binary_sensor.toilet_motion,
          states.binary_sensor.lounge_motion,
          states.binary_sensor.dining_motion,
          states.binary_sensor.bathroom_motion,
          states.binary_sensor.kitchen_motion,
          states.binary_sensor.utility_motion,
          states.binary_sensor.landing_motion,
          states.binary_sensor.office_motion,
          states.binary_sensor.aaron_motion,
          states.binary_sensor.jayden_motion,
          states.binary_sensor.master_motion]
        -%}
        {%- for pir in pirs -%}
          {%- if as_timestamp(pir.last_changed) == as_timestamp(pirs | map(attribute='last_changed') | max) -%}
            {{ pir.entity_id }}
          {%- endif -%}
        {%- endfor -%}