apple_tv_reset_menu:
  alias:  Apple TV Reset Menu
  sequence:
  - wait_template: "{{ is_state('script.turn_on_lounge_media', 'off') }}"
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - menu       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - menu       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - menu       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - menu       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - menu       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - menu       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - menu       
  - delay: 
      milliseconds: 500
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command:
        - top_menu