initial_state: true
alias: Eugene Laptop Idle Update Heartbeat
trigger:
  - platform: template
    value_template: >
      {% set duration_minutes = 3 %}
      {% set last_changed_seconds = as_timestamp(states.input_datetime.eugene_laptop_heartbeat.last_updated) %}
      {% set current_time_seconds = as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M')) %}
      {{ last_changed_seconds + duration_minutes * 60 < current_time_seconds }}
action:
- service: input_boolean.turn_on
  entity_id: input_boolean.eugene_laptop_idle