alias: Master Timer
initial_state: true
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.master_bedroom
condition: []
action:
- service: light.turn_off
  entity_id: light.master_accent
- condition: state
  entity_id: input_boolean.kids_sleeping
  state: 'on'
- service: light.turn_off
  entity_id: light.master