- name: "Lounge_LGTV_CHANNEL +"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEhISEhISEhISNxI3EjcSNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CHANNEL -"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEhISEhISEhISEhI3EjcSNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_VOLUME +"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEhISEhISEhISNxISEjcSNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_VOLUME -"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhISEhISEhISEhISEhISEjcSNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CURSOR RIGHT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEhISEhISEhISNxISEhISNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_RIGHT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEhISEhISEhISNxISEhISNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CURSOR LEFT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxISEhISEhISEhISEhISEhISNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_LEFT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxISEhISEhISEhISEhISEhISNxI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_POWER"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_MUTE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EhISEhISEhISEhI3EjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_I/II"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_MTS"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TV/VIDEO"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhI3EhISEhISEhISEhISEjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_INPUT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhI3EhISEhISEhISEhISEjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TV / VIDEO"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhI3EhISEhISEhISEhISEjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_SLEEP"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxI3EhISEhISEhISNxISEhISEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TV INPUT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxI3EhISEhISEhISEhISEhISEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_0"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEjcSEhISEhISNxI3EjcSNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_1"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEjcSEhISEhISEhI3EjcSNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_2"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEjcSEhISEhISNxISEjcSNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_3"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_4"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEjcSEhISEhISNxI3EhISNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_5"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxISEjcSEhISEhISEhI3EhISNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_6"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEjcSEhISEhISNxISEhISNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_7"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxISEjcSEhISEhISEhISEhISNxISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_8"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EjcSEhISEhISNxI3EjcSEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_9"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EjcSEhISEhISEhI3EjcSEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_BACK"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EjcSEhISEhISNxISEjcSEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_FLASHBACK"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EjcSEhISEhISNxISEjcSEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_Q.VIEW"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EjcSEhISEhISNxISEjcSEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_REVIEW"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EjcSEhISEhISNxISEjcSEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_FAV"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxI3EjcSEhISEhISNxISEhISEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_FRC"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxI3EjcSEhISEhISNxISEhISEhISEjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TEXT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEhISNxISEhISNxI3EjcSNxI3EhISNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TEXT TIME"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEhISNxISEhISNxISEhISNxI3EhISNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_BACK_2"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EhISNxISEhISNxI3EjcSEhI3EhISNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TEXT REVEAL"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EhISNxISEhISNxISEjcSEhI3EhISNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_SUBTITLE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EjcSNxISEhISEhI3EjcSEhISEhISNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CAPTION"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EjcSNxISEhISEhI3EjcSEhISEhISNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CURSOR UP"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEhISEhI3EhISNxI3EjcSNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_UP"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEhISEhI3EhISNxI3EjcSNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CURSOR DOWN"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEhISEhI3EhISEhI3EjcSNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_DOWN"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEhISEhI3EhISEhI3EjcSNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_MENU"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhISEhISEhI3EhISEhISEjcSNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CURSOR ENTER"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEhISEhI3EhISNxI3EhISNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_CURSOR OK"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEhISEhI3EhISNxI3EhISNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_ENTER"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEhISEhI3EhISNxI3EhISNxI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_DASH-"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxI3EhISEhI3EhISNxI3EhISEhI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_--"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxI3EhISEhI3EhISNxI3EhISEhI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_APC"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxI3EhISEhI3EhISEhI3EhISEhI3EjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_INPUT D/A"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_DASP"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_LIST"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhISEjcSEhI3EhISEhISEjcSNxISEjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_A. PROGRAM"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEjcSEhI3EhISNxI3EhISNxISEjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_MEMORY/ERASE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxISEjcSEhI3EhISEhI3EhISNxISEjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_VIDEO 1"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EjcSEhI3EhISEhISEhISEhISEhISEhISEgAFrgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_VIDEO 1_2"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EjcSEhI3EhISNxISEjcSEhISEjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_EXIT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhI3EjcSEhI3EhISEhISEjcSEhISEjcSEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_PIP/ DW"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEhISNxI3EhISNxI3EjcSNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_COLOR 4 BLUE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEhISNxI3EhISEhI3EjcSNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_PIP INPUT"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEhISNxI3EhISEhI3EjcSNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TEXT UPDATE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEhISNxI3EhISNxISEjcSNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_WINDOW POSITION"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEhISNxI3EhISNxISEjcSNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_COLOR 3 YELLOW"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhISEhISNxI3EhISEhISEjcSNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_SWAP"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhISEhISNxI3EhISEhISEjcSNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_WINDOW SIZE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEhISNxI3EhISNxI3EhISNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TEXT HOLD"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxISEhISNxI3EhISEhI3EhISNxI3EhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TEXT INDEX"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEjcSNxI3EhISNxI3EjcSNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_COLOR 2 GREEN"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEjcSNxI3EhISEhI3EjcSNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_COLOR 1 RED"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEjcSNxI3EhISNxISEjcSNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_PIP CH -"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEjcSNxI3EhISNxISEjcSNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_PIP CH+"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEjcSNxI3EhISNxISEjcSNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_4:3"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEjcSNxI3EhISNxISEhISNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_16:9"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxISEjcSNxI3EhISEhISEhISNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_RATIO"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EjcSNxI3EhISEhI3EjcSEhISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_ARC"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EjcSNxI3EhISEhI3EjcSEhISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_SPLIT ZOOM"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhI3EjcSNxI3EhISEhISEjcSEhISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_SIMPLINK"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxI3EjcSNxI3EhISNxISEhISEhISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_MULTIMEDIA"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EjcSEhISEjcSNxI3EjcSEhISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TV GUIDE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EhISNxISEjcSEhI3EjcSEhI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_INFO"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhI3EhISNxISEjcSNxISEjcSEhI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_GUIDE"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhI3EhISNxISEjcSEhISEjcSEhI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_COMPONET"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxI3EjcSNxISEjcSEhISEhISEhISEhISEhISEgAFPwABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_COMPONENT 1"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxI3EjcSNxISEjcSEhISEhISEhISEhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_POWER ON"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEhISEhI3EjcSNxI3EhISNxI3EjcSEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_POWER OFF"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxISEhISEhI3EjcSEhI3EhISNxI3EjcSEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_DVI"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEhISEhI3EjcSNxISEhISNxI3EjcSEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_VIDEO 2"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEjcSEhI3EjcSNxI3EjcSNxISEjcSEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_RGB"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxISEjcSEhI3EjcSEhI3EhISNxISEjcSEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TV"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEjcSEhI3EjcSNxISEhISNxISEjcSEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_BRIGHTNESS +"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEhISNxI3EjcSNxI3EjcSNxI3EhISEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_BRIGHTNESS -"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EhISEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

- name: "Lounge_LGTV_TV/RADIO"
  command_on: 'JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEjcSNxI3EjcSNxI3EjcSNxISEhISEhISEgAFGgABKEoSAAxWDQUAAAAAAAA='

