alias: Door Lock Checks
initial_state: true
trigger:
  - platform: state
    entity_id:
      - binary_sensor.back_door
      - binary_sensor.front_door
      - binary_sensor.lounge_door
      - binary_sensor.dining_door
      - binary_sensor.garage_back_door
    from: 'off'
    to: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: 'input_boolean.{{ trigger.entity_id.split(".")[1] }}_checked' # Get the second part of the entity id
