alias: Doors Opened
initial_state: true
trigger:
- to: 'on'
  platform: state
  entity_id: binary_sensor.xiaomi_front_door_contact
- to: 'on'
  platform: state
  entity_id: binary_sensor.xiaomi_patio_door_contact
- to: 'on'
  platform: state
  entity_id: binary_sensor.xiaomi_back_door_contact
condition:  
action:
- service: script.speech_engine
  data:
    call_door_check: 1
    call_window_check: 1
- service: script.tts_all
  data:
    message: "{{ states('input_text.notification_message') }}"
# - service: script.tts_all
#   data_template:
#     message: '{{ trigger.to_state.attributes.friendly_name }} door opened.'
- service: timer.cancel
  data_template:
    entity_id: timer.{{trigger.entity_id | regex_replace(find='xiaomi_', replace='', ignorecase=True) | regex_replace(find='_contact', replace='', ignorecase=True) }}
- service: timer.start
  data_template:
    entity_id: timer.{{trigger.entity_id | regex_replace(find='xiaomi_', replace='', ignorecase=True) | regex_replace(find='_contact', replace='', ignorecase=True) }}
    duration: 00:10:00