alias: Door Lock Checks
initial_state: true
trigger:
  - platform: event
    event_type: tag_scanned
action:
  - service: input_boolean.turn_on
    data:
      entity_id: 'input_boolean.{{ trigger.event.data.tag_id }}_checked'
