alias: Windows Opened Announcement
initial_state: true
trigger:
- platform: state
  to: 'on'
  entity_id:
    - binary_sensor.kitchen_window
    - binary_sensor.toilet_window
    - binary_sensor.lounge_left_window
    - binary_sensor.lounge_right_window
condition:  
action:
- service: script.tts_kitchen
  data_template:
    message: '{{ trigger.to_state.attributes.friendly_name }} opened.'