alias: Action Disable Motion
initial_state: true
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: 'Disable_Motion'
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.motion_enabled