alias: Arrive Home TTS
initial_state: true
trigger:
- entity_id:  binary_sensor.eugene, binary_sensor.hailey
  platform: state
  to: 'on'
action:
- service: script.tts_all
  data_template:
    message: '{{ trigger.to_state.attributes.friendly_name }} is home'
- service: notify.iphones
  data_template:
    message: '{{ trigger.to_state.attributes.friendly_name }} is home'
