alias: bathroom Timer
initial_state: true
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.bathroom
condition: []
action:
- service: light.turn_off
  data:
    transition: 3
    entity_id: light.bathroom