- platform: mqtt
  name: Floor Sonoff
  state_topic: "stat/floor_light/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/floor_light/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: Christmas Indoor Sonoff
  state_topic: "stat/christmas_indoor/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/christmas_indoor/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: Plug 1
  state_topic: "plug/stat/smart_plug_1/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "plug/cmnd/smart_plug_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: Plug 2
  state_topic: "plug/stat/smart_plug_2/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "plug/cmnd/smart_plug_2/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: Plug 3
  state_topic: "plug/stat/smart_plug_3/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "plug/cmnd/smart_plug_3/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: Plug 4
  state_topic: "plug/stat/smart_plug_4/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "plug/cmnd/smart_plug_4/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: Plug 5
  state_topic: "plug/stat/smart_plug_5/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "plug/cmnd/smart_plug_5/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false