alias: Sunset Close Blinds
initial_state: true
trigger:
- platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state_attr('sun.sun', 'elevation') }}"
  below: 2.5
condition: []
action:
- service: cover.close_cover
  entity_id: cover.lounge_blind