alaram_panic:
  initial: off
  icon: mdi:alarm-bell

lounge_motion_lights_disabled:
  icon: mdi:motion-sensor-off

notify_eugene_telegram:
  initial: on

back_door_checked:
  icon:  mdi:door-closed-lock

front_door_checked:
  icon:  mdi:door-closed-lock

lounge_door_checked:
  icon:  mdi:door-closed-lock

dining_door_checked:
  icon:  mdi:door-closed-lock

garage_back_door_checked:
  icon:  mdi:door-closed-lock
