ac_left_on:
  alias: AC Left On Check
  sequence:
  - condition: or
    conditions:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.master_motion.last_changed)) >= 3600 }}"
        - condition: template
          value_template: "{{ not is_state('climate.melcloud_master_176430','off') }}"
        - condition: state
          entity_id: input_boolean.is_bedtime
          state: 'off'
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.lounge_motion.last_changed)) >= 3600 }}"
        - condition: template
          value_template: "{{ not is_state('climate.melcloud_lounge_174962','off') }}"
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.jayden_motion.last_changed)) >= 3600 }}"
        - condition: template
          value_template: "{{ not is_state('climate.melcloud_jayden_177589','off') }}"
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.aaron_motion.last_changed)) >= 3600 }}"
        - condition: template
          value_template: "{{ not is_state('climate.melcloud_aaron_177590','off') }}"
  - service: script.speech_engine
    data:
      call_ac_watchdog: 1