good_night:
  alias: Good Night
  sequence:
  - service: homeassistant.turn_off
    entity_id: 
    - group.downstairs_lights
    - group.upstairs_lights
  - service: input_boolean.turn_on
    entity_id: input_boolean.is_bedtime
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.yale_smart_alarm
  - wait_template: "{{states('alarm_control_panel.yale_smart_alarm') == 'armed_home'}}"
  - service: script.speech_engine
    data:
      call_alarm_check: 1
      call_window_check: 1
      call_door_check: 1
      call_ac_watchdog: 1
      call_check_lights_count: 1
      type: tts
  - service: script.tts
    data:
      device: master
      message: "{{ states('input_text.tts_message') }}"